apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-gke-nodepool
  labels:
    crossplane.io/xrd: compositenodepools.demo.anthos.com
    provider: gcp
    cluster: gke
spec:
  compositeTypeRef:
    apiVersion: demo.anthos.com/v1
    kind:  CompositeNodepool
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: nodepool
    base:
      apiVersion: container.gcp.upbound.io/v1beta1
      kind: NodePool
      metadata:
        annotations:
          meta.upbound.io/example-id: container/v1beta1/nodepool
        #labels:
        #  testing.upbound.io/example-name: nodepool
      spec:
        providerConfigRef: 
          name: default
          clusterRef:
            name: test-cluster
          location: us-central1-a
          nodeConfig:
            - machineType: e2-medium
              oauthScopes:
                - https://www.googleapis.com/auth/cloud-platform
              serviceAccount: 261832825633-compute@developer.gserviceaccount.com
              nodeLocations: 
                - us-central1-a
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.minNodeCount
      toFieldPath: spec.forProvider.nodeCount
    - fromFieldPath: spec.parameters.clusterName
      toFieldPath: spec.forProvider.clusterRef.name
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.forProvider.nodeConfig[0].machineType
      transforms:
        - type: map
          map:
            small: e2-small
            medium: e2-medium
            large: e2-standard-2