apiVersion: gcp.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-gcp-cluster
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: testhooks/delete-release.sh
spec:
  compositionSelector:
    matchLabels:
      provider: provider-gcp
  id: platform-ref-gcp-cluster
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "34.5.1"
  writeConnectionSecretToRef:
    name: cluster-conn