apiVersion: demo.anthos.com/v1
kind: CompositeCluster 
metadata:
  name: test-cluster2
spec:
  compositionRef:
    # Possible values cluster-gcp-gke, cluster-aws-eks, cluster-azure-aks
    name: cluster-gcp-gke
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    k8sVersion: "1.25"
    fleetProject: "873051588019"
    minNodeCount: 0
    adminUsers:
    - admin@rickruguichen.altostrat.com  
  writeConnectionSecretToRef:
    namespace: default
    name: team-a